spring.application.name=configuration-server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/nish2008/review-application-microservices-master.git
spring.cloud.config.server.git.default-label=config_server_implemented

#spring.cloud.config.server.git.uri=${user.home}\\review-application-microservices-master
#spring.cloud.config.server.git.repos.local=
spring.cloud.config.server.git.search-paths=config

#eureka
eureka.instance.hostname=${EUREKA_HOST:localhost}
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
eureka.instance.preferIpAddress=true


#management.endpoints.web.exposure.include=refresh
#http://localhost:8080/actuator/refresh need to use refresh from actuator
